Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,25 +25,33 @@ jobs:
        npm install -g newman-reporter-htmlextra
        
     - name: Make Directory for test results
-      run: mkdir -p newman
+      run: mkdir -p reports
       
     - name: Run postman collection
       if: always()
       run: |
-       newman run ./api/florkashop-marketing.json -e ./api/prod-env.json -r htmlextra,cli,junit --reporter-htmlextra-export newman/htmlreport.html --reporter-junit-export newman/junit.xml
+       newman run ./api/florkashop-marketing.json -e ./api/prod-env.json -r htmlextra,cli,junit --reporter-htmlextra-export reports/htmlreport.html --reporter-junit-export reports/junit.xml
    
-    - name: Publish Test Report
-      uses: mikepenz/action-junit-report@v3
-      if: always() 
+#     - name: Publish Test Report
+#       uses: mikepenz/action-junit-report@v3
+#       if: always() 
+#       with:
+#          report_paths: 'newman/junit.xml'
+
+    - name: Test Report
+      uses: dorny/test-reporter@v1.4.0
+      if: success() || failure()    # run this step even if previous step failed
       with:
-         report_paths: 'newman/junit.xml'
+        name: JEST Tests            # Name of the check run which will be created
+        path: reports/junit-*.xml    # Path to test results
+        reporter: jest-junit 
      
     - name: Output the run Details
       uses: actions/upload-artifact@v2
       if: always()
       with:
        name: newman-test-results
-       path: newman
+       path: reports
        
        
 
